name: Build and Release Jar

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Parse commit message
        id: parse_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          # Use regex to detect if commit is a new version release
          if [[ "$COMMIT_MSG" =~ ^\[New\ Version\]\ ([^|]*)\ \|\ (.*)$ ]]; then
            JAR_NAME="${BASH_REMATCH[1]}"
            DESCRIPTION="${BASH_REMATCH[2]}"
            VERSION_TAG=$(echo "$JAR_NAME" | sed -E 's/.*-v([0-9]+\.[0-9]+\.[0-9]+)\.jar/\1/')
            RELEASE_NAME=$(echo "$JAR_NAME" | sed -E 's/\.jar//' | tr '-' ' ')
            echo "Detected version: $VERSION_TAG"
            echo "Jar name: $JAR_NAME"
            echo "Release name: $RELEASE_NAME"
            echo "::set-output name=jar_name::$JAR_NAME"
            echo "::set-output name=description::$DESCRIPTION"
            echo "::set-output name=version_tag::$VERSION_TAG"
            echo "::set-output name=release_name::$RELEASE_NAME"
          else
            echo "No new version detected, skipping build."
            exit 0
          fi

      - name: Build with ShadowJar
        if: steps.parse_commit.outputs.jar_name
        run: ./gradlew shadowJar

      - name: Rename jar file
        if: steps.parse_commit.outputs.jar_name
        run: |
          JAR_PATH=$(find build/libs -name '*.jar' | head -n 1)
          mv "$JAR_PATH" "build/libs/${{ steps.parse_commit.outputs.jar_name }}"
          echo "Renamed jar to ${{ steps.parse_commit.outputs.jar_name }}"

      - name: Create Git Tag
        if: steps.parse_commit.outputs.jar_name
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git tag -a "v${{ steps.parse_commit.outputs.version_tag }}" -m "Release version ${{ steps.parse_commit.outputs.version_tag }}"
          git push origin "v${{ steps.parse_commit.outputs.version_tag }}"
          echo "Created tag v${{ steps.parse_commit.outputs.version_tag }}"

      - name: Create GitHub Release
        if: steps.parse_commit.outputs.jar_name
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.parse_commit.outputs.version_tag }}"
          name: ${{ steps.parse_commit.outputs.release_name }} # Use the formatted release name
          files: build/libs/${{ steps.parse_commit.outputs.jar_name }}
          body: ${{ steps.parse_commit.outputs.description }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
